
RESOURCE_DISPLAY_NAME_DOC = 'Наименование отображающие на внешних сервисах.'
RESOURCE_NAME_DOC = 'Внутренние наименование'
RESOURCE_DESCRIPTION_DOC = 'Описание'

RESOURCE_DISPLAY_NAME_MAX_LENGTH = 128
RESOURCE_NAME_MAX_LENGTH = RESOURCE_DISPLAY_NAME_MAX_LENGTH
RESOURCE_DESCRIPTION_MAX_LENGTH = 2048
